need to source /opt/ros/${ROS_DISTRO}/setup.bash, before source ~/coral_ws/deve/setup.bash
otherwise we got
```
$ roslaunch
Traceback (most recent call last):
  File "/opt/ros/melodic/bin/roslaunch", line 34, in <module>
    import roslaunch
ImportError: No module named roslaunch
```